### PR TITLE
Add example for Elixir - Phoenix

### PR DESCRIPTION
**Pull request by Rutaba**

### CODE REVIEW

**Comment by rowan-m** [comment]
Thanks! I will say, it took me a little while to work out what Elixir / Plug actually was… you may want to consider adding a little description to the repos making it clear it's an Erlang thing.

**Comment by rowan-m** [comment]
I'll update this, link in from the home page, and merge.

**Comment by rowan-m** [comment]
Oh, wait… I see, Elixir is the language just running on ErlangVM.

**Comment by Rutaba** [comment]
@rowan-m yeah Elixir is the language built on the ErlangVM and Phoenix is it's web framework. Actually I wrote the example with this assumption that the developers who'll look for this particular example would have the know-how of this language and the plugs. I appologize for the inconvenience

**Pull request merged**
